[project]
name = "the-people-around-you"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.7",
    "django-cors-headers>=4.9.0",
    "django-simple-history>=3.13.0",
    "pillow>=12.3.0",
    "python-decouple>=3.8",
]
