# Generated by Django 4.1.2 on 2022-10-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='angle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='user',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='user',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
