# Generated by Django 4.1.2 on 2022-10-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_angle_user_avatar_user_scale_user_x_user_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=128)),
                ('last_name', models.CharField(default='', max_length=128)),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to='avatars')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('angle', models.IntegerField(default=0)),
                ('scale', models.FloatField(default=1.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='angle',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='user',
            name='x',
        ),
        migrations.RemoveField(
            model_name='user',
            name='y',
        ),
    ]
