# Generated by Django 4.1.2 on 2022-10-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_options_person_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='angle',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
