# Generated by Django 4.1.2 on 2023-02-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_person_angle_alter_person_x_alter_person_y'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'created_by'), name='unique_person_name_per_creator'),
        ),
    ]
