# Generated by Django 4.1.2 on 2023-02-15 20:41

import os
import shutil

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_avatar_imagefield_to_image_model(apps, schema_editor):
    Person = apps.get_model("core", "Person")
    Image = apps.get_model("core", "Image")
    PersonImage = apps.get_model("core", "PersonImage")
    print()

    target_dir = os.path.join(settings.MEDIA_ROOT, "images")
    if not os.path.isdir(target_dir):
        os.makedirs(target_dir)

    for person in Person.objects.all():
        if not person.avatar.name:
            continue

        avatar_source_filepath = person.avatar.path
        avatar_target_filepath = os.path.join(
            target_dir, person.avatar.name.replace("avatars/", "")
        )
        shutil.copyfile(avatar_source_filepath, avatar_target_filepath)

        image = Image()
        image.file = avatar_target_filepath
        image.save()

        PersonImage.objects.create(person=person, image=image)
        print(person, "avatar migrated to Image model")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_person_unique_person_name_per_creator"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("file", models.ImageField(upload_to="images")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.image"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.person"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(
            migrate_avatar_imagefield_to_image_model, migrations.RunPython.noop
        ),
    ]
