# Generated by Django 4.1.2 on 2023-02-15 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_image_personimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_images', to='core.image'),
        ),
        migrations.AlterField(
            model_name='personimage',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_images', to='core.person'),
        ),
    ]
