# Generated by Django 4.1.2 on 2023-02-19 21:49

from django.db import migrations, models
from django.core.files.base import ContentFile
from django.conf import settings
import os


def populate_preview_from_file(apps, schema_editor):
    Image = apps.get_model("core", "Image")
    print()
    for image in Image.objects.all():
        rel_path = image.file.path.replace(str(settings.MEDIA_ROOT) + os.sep, "")
        image.file = rel_path
        image.save()

    print()
    for image in Image.objects.all():
        ext = os.path.splitext(image.file.name)
        image.preview = ContentFile(
            image.file.read(),
            name=image.file.name.replace(f".{ext}", f"_preview.{ext}"),
        )
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_personimage_image_alter_personimage_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="preview",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="images"
            ),
        ),
        migrations.RunPython(populate_preview_from_file, migrations.RunPython.noop),
    ]
