# Generated by Django 4.1.2 on 2023-02-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_image_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='avatar',
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
