# Generated by Django 4.1.2 on 2023-02-20 17:08

from django.db import migrations, models


def merge_first_last_names(apps, schema_editor):
    Person = apps.get_model("core", "Person")
    for person in Person.objects.all():
        person.name = person.first_name.strip() + " " + person.last_name.strip()
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_person_avatar_person_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="name",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.RunPython(merge_first_last_names, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="person",
            name="unique_person_name_per_creator",
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                fields=("name", "created_by"), name="unique_person_name_per_creator"
            ),
        ),
        migrations.RemoveField(
            model_name="person",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="person",
            name="last_name",
        ),
    ]
