# Generated by Django 4.1.2 on 2023-03-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_person_date_of_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
